name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Draft Release

    runs-on: ubuntu-latest

    # only run on release commits either created by the version action or created manually
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
