name: Version

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Version

    runs-on: ubuntu-latest

    # only run on commits to main branch that is not a result of this action
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.VERSION_TOKEN }}

      - run: |
          git config --global user.email "eriicafes@gmail.com"
          git config --global user.name "Eric Afes"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Bump Version
        run: |
          npm ci
          npm run build
          node lib/cli release
